services:
  sypago_checkout:
    image: orlandoiii/sypago_checkout:1.0.8
    ports:
      - "3500:3000"
    volumes:
      - /app/sypago_checkout/rest_api/config.json:/app/public/config.json
      - /app/sypago_checkout/rest_api/checkoutweb:/app/checkoutweb

    container_name: sypago_checkout
    restart: always

